[shared_icons]
"3gp" = "video"
"7z" = "archive"
"apk" = "mobile"
"appx" = "package"
"appxbundle" = "package"
"avi" = "video"
"bat" = "script"
"bmp" = "image"
"cab" = "package"
"cda" = "audio"
"cmd" = "script"
"conf" = "config"
"dll" = "library"
"docx" = "doc"
"flac" = "audio"
"gif" = "image"
"gsm" = "audio"
"gz" = "archive"
"ico" = "image"
"ini" = "config"
"ipa" = "mobile"
"iso" = "diskimage"
"jpeg" = "image"
"jpg" = "image"
"m4a" = "audio"
"markdown" = "md"
"mkv" = "video"
"mp3" = "audio"
"mp4" = "video"
"msi" = "package"
"odt" = "doc"
"pem" = "crt"
"png" = "image"
"pptx" = "ppt"
"rar" = "archive"
"reg" = "txt"
"rtf" = "doc"
"sh" = "script"
"sql" = "db"
"svg" = "image"
"tar" = "archive"
"toml" = "ml"
"wav" = "audio"
"webm" = "video"
"webp" = "image"
"xlsx" = "xls"
"xz" = "archive"
"yaml" = "ml"
"yml" = "ml"
"zip" = "archive"
