[shared_icons]
"123" = "xls"
"3gp" = "video"
"7z" = "archive"
"accda" = "db"
"accdb" = "db"
"accde" = "db"
"accdr" = "db"
"accdt" = "db"
"accdu" = "db"
"apk" = "mobile"
"appx" = "package"
"appxbundle" = "package"
"avi" = "video"
"bat" = "script"
"bmp" = "image"
"cab" = "package"
"cda" = "audio"
"cgm" = "ppt"
"cmd" = "script"
"conf" = "config"
"dif" = "xls"
"dll" = "library"
"docm" = "doc"
"docx" = "doc"
"dot" = "doc"
"dotm" = "doc"
"dotx" = "doc"
"flac" = "audio"
"fodp" = "ppt"
"fods" = "xls"
"fodt" = "doc"
"gif" = "image"
"gsm" = "audio"
"gz" = "archive"
"ico" = "image"
"ini" = "config"
"ipa" = "mobile"
"iso" = "diskimage"
"jpeg" = "image"
"jpg" = "image"
"m4a" = "audio"
"markdown" = "md"
"mkv" = "video"
"mp3" = "audio"
"mp4" = "video"
"msi" = "package"
"odg" = "ppt"
"odp" = "ppt"
"ods" = "xls"
"odt" = "doc"
"ogg" = "audio"
"one" = "txt"
"otp" = "ppt"
"ots" = "xls"
"ott" = "doc"
"pdb" = "doc"
"pem" = "crt"
"png" = "image"
"pot" = "ppt"
"potm" = "ppt"
"ppa" = "ppt"
"pps" = "ppt"
"ppsm" = "ppt"
"ppsx" = "ppt"
"pptm" = "ppt"
"pptx" = "ppt"
"psw" = "doc"
"pub" = "txt"
"rar" = "archive"
"reg" = "txt"
"rtf" = "doc"
"sdc" = "xls"
"sdw" = "doc"
"sgl" = "doc"
"sh" = "script"
"sldm" = "ppt"
"sldx" = "ppt"
"so" = "library"
"sql" = "db"
"stc" = "xls"
"stw" = "doc"
"svg" = "image"
"sxc" = "xls"
"sxw" = "doc"
"tar" = "archive"
"toml" = "ml"
"uof" = "txt"
"uop" = "ppt"
"uot" = "doc"
"vor" = "xls"
"wav" = "audio"
"wb2" = "xls"
"wbk" = "doc"
"webm" = "video"
"webp" = "image"
"wk1" = "xls"
"wks" = "xls"
"wll" = "doc"
"wpd" = "doc"
"wps" = "doc"
"wwl" = "doc"
"xla_" = "xls"
"xla" = "xls"
"xla5" = "xls"
"xlam" = "xls"
"xll_" = "xls"
"xll" = "xls"
"xll8" = "xls"
"xlm" = "xls"
"xlsb" = "xls"
"xlsm" = "xls"
"xlsx" = "xls"
"xlt" = "xls"
"xltm" = "xls"
"xltx" = "xls"
"xlw" = "xls"
"xz" = "archive"
"yaml" = "ml"
"yml" = "ml"
"zip" = "archive"
