# Metadata

language_name = "English"
translated_by = "Translation: Kierownik223"
author = "Made by Kierownik223"

# Header

home = "Home"
settings = "Settings"
log_in = "Log in"
manage_account = "Manage account"
admin = "Admin panel"
log_out = "Log out"

# Settings

sync_settings = "Sync settings"
sync_success = "Settings saved successfully."
fetch_settings = "Fetch settings"
fetch_success = "Settings fetched successfully!"
language = "Language"
theme = "Theme"
change_lang = "Change language (NEW!)"
change_theme = "Change theme"
theme_default = "Default theme"
theme_darkblue = "Dark blue theme"
theme_greenish = "Greenish theme"
theme_antique = "Antique (original) theme"
plain = "Plain HTML"
enable = "Enable"
disable = "Disable"
hires = "High-resolution icons"
smallhead = "Small header logo"
dont_override_settings = "Don't override settings"
save_settings = "Save settings"
reset_settings = "Reset settings"
viewers = "File detail viewers"
use_si_prefixes = "Use SI prefixes"
audio_player = "Use advanced audio player"
video_player = "Use advanced video player"
directory_browser = "Directory browser in the uploader"

# Files

readme = "Information"
download = "Download"
file = "File"
folder = "File folder"
archive = "Archive"
zipviewer_title = "ZIP viewer"
zip_file = "ZIP file"
mdreader_title = "MD reader"
reading_markdown = "Reading file"
file_details = "Details of file"
file_name = "File name"
file_size = "File size"
file_downloads = "Downloads"
print = "Print"
viewing_zip = "Viewing ZIP file"
watching = "Watching file"
download_zip = "Download ZIP"
preparing_zip = "Preparing ZIP..."
rename = "Rename"
rename_success = "Renamed successfully!"
new_name = "New name"
error_renaming = "An error occured while renaming"
create_folder = "New folder"
folder_create_success = "Folder created successfully!"

# Uploader

uploader = "Uploader"
upload = "Upload"
select_file = "Select a file"
upload_success = "uploaded successfully!"
upload_error = "An error occurred while uploading the file."
uploader_title = "File Uploader"
target_dir = "Target directory"
target_placeholder = "Leave empty for /uploads/"
max_size = "Maximum file size allowed is 100MB."
select_folder = "Select a folder"
browse = "Browse"
select_files = "Select files"
uploading = "Uploading"

# Account

username = "Username"
password = "Password"
invalid_info = "Invalid username or password."
log_in_with_marmak = "Log in with a MARMAK Account&trade;"
welcome = "Hi"
tip = "Tip"
settings_tip1 = "If you want to keep your current settings, go to"
settings_tip2 = "and enable „Don't overwrite settings“."
login_to_continue = "Log in to continue to"
remember_me = "Remember me for 30 days"

# Admin

usage = "Usage"
disk_usage = "Disk usage"
sysinfo = "Server information"
memory_usage = "Memory usage"
system = "System"
kernel_version = "Kernel version"
hostname = "Hostname"

# Audio player

listening = "Listening to file"
album = "Album"
year = "Year"
genre = "Genre"
album_cover = "Album cover"
previous = "Previous"
next = "Next"
autoplay = "Autoplay"

# File deletion

delete_success = "removed successfully!"
delete_confirmation = "Are you sure you want to delete"
delete = "Delete"

# Link shortener

shorten = "Shorten"
error_shortening = "An error occurred while shortening the URL."
shortening_ratelimit = "You have shortened too many links. Please try again after an hour."

# Search

search = "Search"
search_engine = "Search"
search_criterion = "Search phrase"
search_placeholder = "Search something!"
search_query_too_short = "Search query must be 3 characters or longer!"

# Errors

error = "Error"
not_found = "Not found"
error_400 = "The client sent an invalid request. Please try again."
error_404 = "The requested resource could not be located. Please double-check the URL and try again."
error_50x = "An internal server error has occurred. Please report this to us."
error_403 = "You don't currently have access to this resource. Please log in as a higher-privileged user."
no_details = "No details available!"
no_video = "Your browser does not support the video element."
no_audio = "Your browser does not support the audio element."
upload_parse_error = "uploaded, but response could not be parsed."
upload_failed_status = "failed with status"
upload_failed_network = "upload failed due to network error."
error_occured = "An error occured:"
error_deleting = "An error occurred while deleting the file."
directory_not_empty = "This directory is not empty!"
upload_not_supported = "The JavaScript uploader is not supported by this browser."
private_folder = "Log in to access private folder!"
file_too_big = "exceeds the maximum allowed upload size."
not_enough_space = "You don't have enough space to upload this file. Please delete some files and try to upload again."
error_creating_folder = "An error occurred while creating the folder."

# Generic UI strings

ok = "OK"
cancel = "Cancel"
others = "others"
cookie_notice = "We use cookies only to store user preferences. If you wish not to use them, don't change anything on this page."
