# Metadata

language_name = "Português"
translated_by = "Tradução por: C4L3B3"
author = "Feito por Kierownik223"

# Header

home = "Início"
settings = "Configurações"
log_in = "Fazer Log in"
manage_account = "Gerenciar conta"
admin = "Painel Admin"
log_out = "Fazer Log out"

# Settings

sync_settings = "Configurações de sincronização"
sync_success = "Configurações salvas com sucesso."
fetch_settings = "Buscar configurações"
fetch_success = "Configurações obtidas com sucesso!"
language = "Idioma"
theme = "Tema"
change_lang = "Trocar idioma (NOVO!)"
change_theme = "Trocar tema"
theme_default = "Tema padrão"
theme_darkblue = "Tema azul escuro"
theme_greenish = "Tema esverdeado"
theme_antique = "Tema antigo (original)"
plain = "HTML simples"
enable = "Ativar"
disable = "Desativar"
hires = "Ícones de alta-resolução"
smallhead = "Logo header pequeno"
dont_override_settings = "Não sobrescrever configurações"
save_settings = "Salvar configurações"
reset_settings = "Redefinir configurações"
viewers = "Visualizadores de detalhes do arquivo"
use_si_prefixes = "Use prefixos SI"
audio_player = "Usar reprodutor de áudio avançado"
video_player = "Usar reprodutor de vídeo avançado"
directory_browser = "Navegador de diretórios no carregador"

# Files

readme = "Informação"
download = "Baixar"
file = "Arquivo"
folder = "Pasta de arquivo(s)"
archive = "Archive"
zipviewer_title = "Visualizador de arquivos ZIP"
zip_file = "Arquivo ZIP"
mdreader_title = "Leitor de MD"
reading_markdown = "Lendo arquivo"
file_details = "Detalhes do arquivo"
file_name = "Nome do arquivo"
file_size = "Tamanho do arquivo"
file_downloads = "Downloads"
print = "Imprimir"
viewing_zip = "Vendo arquivo ZIP"
watching = "Assistindo arquivo"
download_zip = "Baixar ZIP"
preparing_zip = "Preparando ZIP..."
rename = "Renomear"
rename_success = "Renomeado com sucesso!"
new_name = "Novo nome"
error_renaming = "Ocorreu um erro ao renomear"
create_folder = "Criar pasta"
folder_create_success = "Pasta criada com sucesso!"

# Uploader

uploader = "Uploader"
upload = "Enviar/Upload"
select_file = "Selecione um arquivo"
upload_success = "Enviado com sucesso!"
upload_error = "Ocorreu um erro ao enviar o arquivo."
uploader_title = "Uploader de arquivos"
target_dir = "Diretório alvo"
target_placeholder = "Deixar /uploads/ vazio"
target_placeholder_private = "Deixar /private/ vazio"
max_size = "O tamanho máximo de arquivo permitido é 100MB."
select_folder = "Selecionar pasta"
browse = "Pesquisar"
select_files = "Selecione arquivos."
uploading = "Enviando"

# Account

username = "Nome de usuário"
password = "Senha"
invalid_info = "Nome de usuário ou senha inválido(s)"
log_in_with_marmak = "Fazer login com MARMAK Account&trade;"
welcome = "Olá"
tip = "Dica"
settings_tip1 = "Se você quiser manter suas configurações atuais, vá para"
settings_tip2 = "e ative „Não sobrescrever configurações.“."
login_to_continue = "Faça login para continuar para"
remember_me = "Lembre-se de mim por 30 dias"

# Admin

usage = "Uso"
disk_usage = "Uso de disco"
sysinfo = "Informação do servidor"
memory_usage = "Uso de memória"
system = "Sistema"
kernel_version = "Versão do kernel"
hostname = "Nome do host"

# Audio player

listening = "Ouvindo arquivo"
album = "Álbum"
year = "Ano"
genre = "Gênero"
album_cover = "Capa do álbum"
previous = "Anterior"
next = "Próximo"
autoplay = "Reprodução automática"

# File deletion

delete_success = "Removido com sucesso!"
delete_confirmation = "Você tem certeza que quer deletar"
delete = "Deletar"

# Link shortener

shorten = "Encurtar"
error_shortening = "Ocorreu um erro ao encurtar o URL."
shortening_ratelimit = "Você encurtou muitos links. Tente novamente daqui a uma hora."

# Search

search = "Pesquisar"
search_engine = "Mecanismo de busca"
search_criterion = "Frase de pesquisa"
search_placeholder = "Pesquise algo!"
search_query_too_short = "A consulta de pesquisa deve ter pelo menos 3 caracteres!"
search_no_results = "Nenhum resultado encontrado."

# Errors

error = "Erro"
not_found = "Não encontrado"
error_400 = "O cliente enviou um pedido inválido, tente novamente."
error_404 = "Não foi possível localizar o recurso solicitado. Verifique o URL e tente novamente."
error_50x = "Ocorreu um erro interno no servidor. Por favor, informe-nos."
error_403 = "No momento, você não tem acesso a este recurso. Faça login como um usuário com privilégios mais altos."
no_details = "Não há detalhes disponíveis!"
no_audio = "Seu navegador não suporta elemento de áudio."
no_video = "Seu navegador não suporta elemento de vídeo."
upload_parse_error = "Enviado, mas a resposta não pôde ser analisada."
upload_failed_status = "Falhou com status"
upload_failed_network = "O envio falhou devido a um erro de rede."
error_occured = "Ocorreu um erro:"
error_deleting = "Ocorreu um erro ao tentar deletar o arquivo:"
directory_not_empty = "Este diretório não está vazio!"
upload_not_supported = "O carregamento por JavaScript não é suportado por este navegador."
private_folder = "Faça login para acessar a pasta privada!"
file_too_big = "excede o tamanho máximo permitido para upload."
not_enough_space = "Você não tem espaço suficiente para enviar este arquivo. Exclua alguns arquivos e tente enviar novamente."
error_creating_folder = "Ocorreu um erro ao criar a pasta."

# Generic UI strings

ok = "OK"
cancel = "Cancelar"
others = "Outros"
cookie_notice = "Usamos cookies apenas para armazenar preferências do usuário. Se não quiser usá-las, não altere nada nesta página."
