# Metadata

language_name = "Русский"
translated_by = "Перевод: PickaxeInABox"
author = "Создано: Kierownik223"

# Header

home = "Домашняя страница"
settings = "Настройки"
log_in = "Войти"
manage_account = "Управление аккаунтом"
admin = "Панель администратора"
log_out = "Выйти"

# Settings

sync_settings = "Настройки синхронизации"
sync_success = "Настройки загружены в базу данных. Они будут загружены на всех устройствах после следующего входа."
fetch_settings = "Загрузить настройки"
fetch_success = "Настройки были загружены из базы данных."
language = "Язык"
theme = "Тема"
change_lang = "Сменить язык (НОВОЕ!)"
change_theme = "Сменить тему"
theme_default = "Стандартная тема"
theme_darkblue = "Тёмно-зелёная тема"
theme_greenish = "Зеленоватая тема"
theme_antique = "Антик (оригинальная тема)"
plain = "Простой HTML"
enable = "Включить"
disable = "Отключить"
hires = "Иконки высокого разрешения"
smallhead = "Маленький логотип заглавия"
dont_override_settings = "Не перезаписывать настройки"
save_settings = "Сохранить настройки"
reset_settings = "Сбросить настройки"
viewers = "Просмотрщики сведений о файле"
use_si_prefixes = "Используйте приставки SI"
audio_player = "Использовать продвинутый аудиоплеер"
video_player = "Использовать продвинутый видеоплеер"
directory_browser = "Обозреватель каталогов в загрузчике"

# Files

readme = "Информация"
download = "Скачать"
file = "Файл"
folder = "Папка файла"
archive = "Архив"
zipviewer_title = "Просмотрщик ZIP файлов"
zip_file = "Файл ZIP"
mdreader_title = "MD ридер"
reading_markdown = "Читаю файл"
file_details = "Данные файла"
file_name = "Имя файла:"
file_size = "Размер файла:"
file_downloads = "Загрузки:"
print = "Печать"
viewing_zip = "Просмотр ZIP-файла"
watching = "Просмотр файла"
download_zip = "Скачать ZIP"
preparing_zip = "Подготовка ZIP..."
rename = "Переименовать"
rename_success = "Успешно переименовано!"
new_name = "Новое имя"
error_renaming = "Произошла ошибка при переименовании"
create_folder = "Создать папку"
folder_create_success = "Папка успешно создана!"

# Uploader

uploader = "Загрузчик"
upload = "Загрузить"
select_file = "Выбрать файл:"
upload_success = "было успешно загружено!"
upload_error = "Произошла ошибка при загрузке файла."
uploader_title = "Файловый загрузчик MARMAK"
target_dir = "Целевая директория:"
target_placeholder = "Оставьте пустым для /uploads/"
target_placeholder_private = "Оставьте пустым для /private/"
max_size = "Максимальный размер файла — 100MB."
select_folder = "Выбрать папку"
browse = "Обзор"
select_files = "Выберите файлы."
uploading = "Загрузка"

# Account

username = "Логин"
password = "Пароль"
invalid_info = "Неверное имя или пароль."
log_in_with_marmak = "Войти с аккаунтом MARMAK&trade;"
welcome = "Здравствуйте"
tip = "Совет"
settings_tip1 = "Если вы хотите сохранить текущие настройки, перейдите в"
settings_tip2 = "и включите \"Не перезаписывать настройки\"."
login_to_continue = "Войдите, чтобы продолжить на"
remember_me = "Запомните меня на 30 дней"

# Admin

usage = "Использование"
disk_usage = "Использование диска"
sysinfo = "Информация о сервере"
memory_usage = "Использование памяти"
system = "Система"
kernel_version = "Версия ядра"
hostname = "Имя хоста"

# Audio player

listening = "Воспроизведение файла"
album = "Альбом"
year = "Год"
genre = "Жанр"
album_cover = "Обложка альбома"
previous = "Предыдущий"
next = "Следующий"
autoplay = "Автовоспроизведение"

# File deletion

delete_success = "успешно удален!"
delete_confirmation = "Вы уверены, что хотите удалить"
delete = "Удалить"

# Link shortener

shorten = "Сократить"
error_shortening = "Произошла ошибка при сокращении URL."
shortening_ratelimit = "Вы сократили слишком много ссылок. Попробуйте снова через час."

# File sharing

share = "Поделиться"
error_sharing = "При совместном использовании файла произошла ошибка."

# Search

search = "Поиск"
search_engine = "Поисковая система"
search_criterion = "Поисковая фраза"
search_placeholder = "Найдите что-нибудь!"
search_query_too_short = "Поисковый запрос должен содержать не менее 3 символов!"
search_no_results = "Нет результатов поиска."

# Errors

error = "Ошибка"
not_found = "Не найдено"
error_400 = "Неверный запрос. Попробуйте снова."
error_404 = "Ресурс не найден. Проверьте URL и попробуйте снова."
error_50x = "Внутренняя ошибка сервера. Пожалуйста, сообщите нам."
error_403 = "У вас нет доступа к этому ресурсу. Войдите с правами администратора."
no_details = "Нет доступной информации!"
no_video = "Ваш браузер не поддерживает элемент видео."
no_audio = "Ваш браузер не поддерживает элемент аудио."
upload_parse_error = "загружен, но не удалось разобрать ответ."
upload_failed_status = "ошибка со статусом"
upload_failed_network = "ошибка загрузки из-за сетевого сбоя."
error_occured = "Произошла ошибка:"
error_deleting = "Ошибка при удалении файла."
directory_not_empty = "Каталог не пуст!"
upload_not_supported = "Этот браузер не поддерживает загрузку через JavaScript."
private_folder = "Войдите, чтобы получить доступ к приватной папке!"
file_too_big = "превышает максимально допустимый размер загрузки."
not_enough_space = "У вас недостаточно места для загрузки этого файла. Удалите некоторые файлы и попробуйте загрузить его снова."
error_creating_folder = "При создании папки произошла ошибка."

# Generic UI strings

ok = "ОК"
cancel = "Отмена"
others = "другие"
cookie_notice = "Мы используем файлы cookie только для хранения пользовательских настроек. Если вы не хотите их использовать, не меняйте ничего на этой странице."
copied_to_clipboard = "Скопировано в буфер обмена"
full_url_copied = "Полный URL скопирован в буфер обмена."
