# Metadata

language_name = "Ślōnskŏ"
translated_by = "Przełożōne: Maszina"
author = "Zrobjyōne przez Kierownik223"

# Header

home = "Strōna głōwno"
settings = "Ustawiynia"
log_in = "Zaloguj sie"
manage_account = "Zarzōndzaj kōntym"
admin = "Panel admina"
log_out = "Wyloguj sie"

# Settings

sync_settings = "Synchronizuj ustawiynia"
sync_success = "Ustawiynia porzōndnie zapiśane."
fetch_settings = "Pobiyr ustawiynia"
fetch_success = "Ustawiynia pobrane porzōndnie!"
language = "Jyzyk"
theme = "Motyw"
change_lang = "Zmiyn jyzyk (NOWE!)"
change_theme = "Zmiyn motyw"
theme_default = "Domyślny motyw"
theme_darkblue = "Ciemnoniebieski motyw"
theme_greenish = "Zielonawy motyw"
theme_antique = "Starodowny (oryginalny) motyw"
plain = "Prosty HTML"
enable = "Załącz"
disable = "Wyłącz"
hires = "Ikōny we wysokij rozprawie"
smallhead = "Mały znak w głōwce"
dont_override_settings = "Niŏ nadpisuj ustawiyn"
save_settings = "Zapiś ustawiynia"
reset_settings = "Resetuj ustawiynia"
viewers = "Szczegōłowi widzowie ô pliku"
use_si_prefixes = "Używej prefixōw SI"

# Files

readme = "Informacyje"
download = "Pobiyr"
file = "Plik"
folder = "Folder z plikami"
archive = "Archiwum"
zipviewer_title = "ZIP-podglōnd"
zip_file = "ZIP-plik"
mdreader_title = "MD-czitelj"
reading_markdown = "Czyto plik"
file_details = "Szczegōły ô pliku"
file_name = "Miano pliku"
file_size = "Wiylkōść pliku"
file_downloads = "Pobiyrniōnć"
print = "Drukuj"
viewing_zip = "Przeglōndōm ZIP-plik"
watching = "Ôbierōm plik"
download_zip = "Pobierz ZIP"
preparing_zip = "Przygotuwano ZIP..."
rename = "Przemiynić"
rename_success = "Przemiyniynte z powodzeniem!"
new_name = "Nowy mjano"
error_renaming = "Pojawiou sie feler przi przemiynianiu"

# Uploader

uploader = "Uplōder"
upload = "Wgraj"
select_file = "Ôbier plik"
upload_success = "został porzōndnie wgrany!"
upload_error = "Bōł feler przi wgrywaniy pliku."
uploader_title = "Uplōder plikōw"
target_dir = "Folder docelowy"
target_placeholder = "Zostow puste dlo /uploads/"
max_size = "Maksymalno wiylkōść pliku to 100MB."
select_folder = "Ôbier folder"
browse = "Szukej"
select_files = "Ôbier pliki."
uploading = "Wgrywanie"

# Account

username = "Miano używacza"
password = "Hasło"
invalid_info = "Niypoprawne miano abo hasło."
log_in_with_marmak = "Zaloguj sie prze MARMAK kōnto&trade;"
welcome = "Witej"
tip = "Szpila"
settings_tip1 = "Jak chcesz ôstawić terŏźnie ustawiynia, idź do"
settings_tip2 = "i załącz „Niŏ nadpisuj ustawiyn“."
login_to_continue = "Zaloguj sie, coby pódjyńć do"

# Admin

usage = "Użycie"
disk_usage = "Zajyncie dysku"
sysinfo = "Informacyje ô serwerze"
memory_usage = "Zajyncie pamiyńci"
system = "System"
kernel_version = "Wersyjo kernelu"
hostname = "Nŏzwa hŏsta"

# Audio player

listening = "Słuchŏm pliku"
album = "Album"
year = "Rok"
genre = "Rodzaj"
album_cover = "Ôkładka albumu"

# File deletion

delete_success = "skasowany porzōndnie!"
delete_confirmation = "Chcesz naprowde skasować"
delete = "Skasuj"

# Link shortener

shorten = "Skrůcić"
error_shortening = "Při skrůcaniu URL trefiła sie feler."
shortening_ratelimit = "Skrůcił żeś za moc linkōw. Sprōbuj za godzina."

# Errors

error = "Feler"
not_found = "Ni ma"
error_400 = "Klynt wysłŏł niypoprawne żōndanie. Sprōbuj jeszcze raz."
error_404 = "Ni znaleziono tego, co szukoł. Sprawdz adres."
error_50x = "Wynętrzny feler serwera. Daj znać adminowi."
error_403 = "Ni mosz dostympu. Zaloguj sie jako lepszy używŏcz."
no_details = "Brak szczegōłōw!"
no_video = "Twoj przeglōndŏcz niy wspiyrŏ elymyntu wideo."
no_audio = "Twoj przeglōndŏcz niy wspiyrŏ elymyntu audio."
upload_parse_error = "wgrany, ale odpowiedź niy poradziła sie przeczytać."
upload_failed_status = "wgrywanie sie niy udało, status:"
upload_failed_network = "wgrywanie sie niy udało prze sieciowy feler."
error_occured = "Feler sie zdarzōł:"
error_deleting = "Feler przi kasowaniy pliku."
directory_not_empty = "Ten folder niy je pusty!"
upload_not_supported = "Tyn przeglōndorz niy wspiyro ładowanio z JavaScriptym."
private_folder = "Zaloguj się, aby dostać się do prywatnego folderu!"

# Generic UI strings

ok = "OK"
cancel = "Ôdwołŏj"
others = "inksy"
cookie_notice = "Używomy cookies ino do przechowywaniŏ preferyncyj używŏczŏ. Jak niy chcesz ich używŏć, niy zmiynej nic na tyj strōnie."
